<?
$dijitParams = array(
    'title'       => 'About', 
    'class'       => 'tab',
    'href'        => $this->baseUrl() . '/api/v1/about.html',
    'parseOnLoad' => true,
);
$content = '';
if ('about' == $this->current) {
    unset($dijitParams['href'], $dijitParams['parseOnLoad']);
    $dijitParams['selected'] = true;
    $content = $this->render('paste/content/about.phtml');
}
echo $this->contentPane('about', $content, $dijitParams);
