<? 
$dijitParams = array(
    'title'         => 'Active Pastes',
    'class'         => 'tab',
    'href'          => $this->baseUrl() . '/api/paste/v1/content/active-grid.html',
    'parseOnLoad'   => true,
);
$content = '';
if ('active' == $this->current) {
    unset($dijitParams['href']);
    $dijitParams['selected'] = true;
    $content = $this->render('paste/content/active-grid.phtml');
}

echo $this->contentPane('active', $content, $dijitParams);
