<? if (isset($this->message)): ?>
    <p class="error"><?= $this->escape($this->message) ?></p>
<? else: ?>
    <h3 class="pastebin-display">
        Code 
        <? if ('text' != $this->paste['type']): ?>
        (<a id="format-toggle" href="#" onClick="paste.unformattedShow();">unformatted</a>)
        <? endif ?>
        <span class="permalink">[<a href="<?= $this->url(array('id' => $this->paste['id'])) ?>">Permalink</a>]</span>
    </h3>
    <div id="pastecode" class="highlight">
        <pre><code class="<?= $this->paste['type'] ?>"><?= $this->escape($this->paste['code']) ?></code></pre>
    </div>
    <? if (!empty($this->paste['summary'])): ?>
    <h3>Summary</h3>
    <p class="summary"><?= $this->escape($this->paste['summary']) ?></p>
    <? endif ?>
    <p id="metadata">
        <?= $this->paste['type'] ?> code pasted <?= $this->paste['created'] ?>
        <?= (empty($this->paste['user'])) ? '' : ' by ' . $this->escape($this->paste['user']) ?>
        <?= (empty($this->paste['expires'])) ? '' : '; expires ' . $this->paste['expires'] ?>
    </p>
    <? if (!empty($this->paste['parent'])): ?>
    <p class="parent">
        <a href="<?= $this->url(
            array(
                'controller' => 'paste',
                'action'     => 'display',
                'id'         => $this->paste['parent'],
            ),
            'default',
            true
        ) ?>">Parent paste (<?= $this->paste['parent'] ?>)</a>
    </p>
    <? endif ?>
    <? if (!empty($this->paste['children'])): ?>
    <p class="children">Child pastes:</p>
    <ul class="children">
    <? foreach ($this->paste['children'] as $child): ?>
        <li><a href="<?= $this->url(
            array(
                'controller' => 'paste',
                'action'     => 'display',
                'id'         => $child,
            ),
            'default',
            true
        ) ?>"><?= $child ?></a></li>
    <? endforeach ?>
    </ul>
    <? endif ?>
<? endif ?>
<?
    $this->dojo()->addOnLoad('paste.setStatusFromMetadata');
    if ('text' == $this->paste['type']) {
        return;
    }
    switch ($this->paste['type']) {
        case 'html':
            $this->dojo()->requireModule('dojox.highlight.languages.html');
            break;
        case 'xml':
            $this->dojo()->requireModule('dojox.highlight.languages.xml');
            break;
        case 'php':
            $this->dojo()->requireModule('paste.highlight.php');
            break;
        case 'python':
            $this->dojo()->requireModule('dojox.highlight.languages.python');
            break;
        default:
            $this->dojo()->requireModule('dojox.highlight.languages._www');
            break;
    }
    $this->dojo()->addOnLoad('paste.formattedShow');
