<?=  $this->contentPane('followup', '', array(
    'title'       => 'Followup', 
    'class'       => 'tab', 
    'href'        => $this->url(
        array(
            'controller' => 'paste',
            'action'     => 'followup',
            'id'         => $this->id,
            'format'     => 'ajax',
        ),
        'default',
        true
    ), 
    'parseOnLoad'   => true,
    'refreshOnShow' => true)) ?>

