<?  $this->contentPane()->captureStart('new-paste', array('title' => 'New Paste', 'class' => 'tab', 'href' => '/paste/new/format/ajax', 'parseOnLoad' => true)) ?>
<script type="dojo/connect" event="onLoad">
    dojo.connect(dojo.byId('pasteform'), 'onsubmit', function () {
        dojo.byId('pasteform-code').value = dijit.byId('pasteform-codeEditor').getValue(false);
    });
</script>
<?= $this->contentPane()->captureEnd('new-paste') ?>

