<? 
Zend_Dojo_View_Helper_Dojo::setUseDeclarative(); 
$this->dojo()->addStylesheet('/js/dojox/grid/_grid/tundraGrid.css')
             ->requireModule('dojox.data.QueryReadStore')
             ->requireModule('dojox.grid.Grid');
?>
<span dojoType="dojox.data.QueryReadStore" jsId="activeStore"
    url="/paste/active-data/format/ajax"></span>
<span dojoType="dojox.grid.data.DojoData" jsId="activeModel"
    store="activeStore" rowsPerPage="30"></span>
<table id="activePastes" dojoType="dojox.grid.Grid" model="activeModel"
    clientSort="false" query="{ id: '*' }" delayScroll="true">
    <script type="dojo/method" event="onSelected" args="inRowIndex">
var row = dijit.byId("activePastes").model.getRow(inRowIndex);
location.href = "/paste/display/id/" + row.id;
    </script>
    <thead>
        <tr>
            <th field="id" width="16em">ID</th>
            <th field="type">Type</th>
            <th field="user">User</th>
            <th field="summary">Summary</th>
            <th field="expires">Expires</th>
        </tr>
    </thead>
</table>

