<? 
Zend_Dojo_View_Helper_Dojo::setUseDeclarative(); 
$this->dojo()->addStylesheet($this->baseUrl() . '/js/dojox/grid/_grid/tundraGrid.css')
             ->requireModule('dojox.data.QueryReadStore')
             ->requireModule('dojox.grid.DataGrid');
?>
<span dojoType="dojox.data.QueryReadStore" jsId="activeStore"
    url="<?= $this->url(
        array(
            'controller' => 'paste',
            'action'     => 'active-data',
            'format'     => 'ajax',
        ),
        'default',
        true
    ) ?>"></span>
<table id="activePastes" dojoType="dojox.grid.DataGrid" store="activeStore"
    jsId="activeGrid" rowsPerPage="30" selectionMode="single" 
    clientSort="false" query="{ id: '*' }" delayScroll="true">
    <script type="dojo/method" event="onClick" args="evt">
var row = activeGrid.selection.getFirstSelected();
paste.tabs.loadPasteTabs(row.i.id);
    </script>
    <thead>
        <tr>
            <th field="id" width="16em">ID</th>
            <th field="type">Type</th>
            <th field="user">User</th>
            <th field="summary">Summary</th>
            <th field="expires">Expires</th>
        </tr>
    </thead>
</table>

