<?  $this->dojo()->enable() ?>
<?  $this->tabContainer()->captureStart('pastebin', array('class' => 'paste-tab')) ?>
<?= $this->render('paste/_about.phtml') ?>
<?= $this->render('paste/_new-paste.phtml') ?>
<?= $this->contentPane('active', '', array(
    'title'       => 'Active Pastes',
    'class'       => 'tab',
    'href'        => $this->url(
        array(
            'controller' => 'paste',
            'action'     => 'active',
            'format'     => 'ajax',
        ),
        'default',
        true
    ),
    'parseOnLoad' => true)) ?>
<?= $this->contentPane('paste', '', array(
    'title'       => $this->title,
    'class'       => 'tab',
    'href'        => $this->url(
        array(
            'controller' => 'paste',
            'action'     => 'display',
            'id'         => $this->id,
            'format'     => 'ajax',
        ),
        'default',
        true
    ),
    'parseOnLoad' => true)) ?>
<?  $this->contentPane()->captureStart('followup', array('title' => 'Followup', 'class' => 'tab', 'selected' => true)) ?>
    <? if (isset($this->message)): ?>
    <h2>Error</h2>
    <p><?= $this->escape($this->message) ?></p>
    <? else: ?>
    <?= $this->form ?>
    <? endif ?>
<?= $this->contentPane()->captureEnd('followup') ?>
<?= $this->tabContainer()->captureEnd('pastebin') ?>
