<?  $this->dojo()->enable() ?>
<?  $this->tabContainer()->captureStart('pastebin', array('class' => 'paste-tab')) ?>
<?= $this->render('paste/_about.phtml') ?>
<?= $this->render('paste/_new-paste.phtml') ?>
<?= $this->contentPane('active', '', array('title' => 'Active Pastes', 'class' => 'tab', 'href' => '/paste/active/format/ajax', 'parseOnLoad' => true)) ?>
<?= $this->contentPane('paste', '', array('title' => $this->title, 'class' => 'tab', 'href' => '/paste/display/id/' . $this->id . '/format/ajax', 'parseOnLoad' => true)) ?>
<?  $this->contentPane()->captureStart('followup', array('title' => 'Followup', 'class' => 'tab', 'selected' => true)) ?>
    <?= $this->form ?>
<?= $this->contentPane()->captureEnd('followup') ?>
<?= $this->tabContainer()->captureEnd('pastebin') ?>
