<?  $this->dojo()->enable() ?>
<?  $this->tabContainer()->captureStart('pastebin', array('class' => 'paste-tab')) ?>
<?= $this->render('paste/_about.phtml') ?>
<?= $this->render('paste/_new-paste.phtml') ?>
<?= $this->contentPane('active', '', array(
    'title'       => 'Active Pastes',
    'class'       => 'tab',
    'href'        => $this->baseUrl() . '/paste/active/format/ajax',
    'parseOnLoad' => true)) ?>
<?= $this->tabContainer()->captureEnd('pastebin') ?>
