<?  $this->dojo()->enable() ?>
<?  $this->tabContainer()->captureStart('pastebin', array('class' => 'paste-tab')) ?>
<?= $this->render('paste/_about.phtml') ?>
<?  $this->contentPane()->captureStart('new-paste', array('title' => 'New Paste', 'class' => 'tab', 'selected' => true)) ?>
<?= $this->form ?>
<?= $this->contentPane()->captureEnd('new-paste') ?>
<?= $this->tabContainer()->captureEnd('pastebin') ?>
