<?
if (isset($this->id)) {
    $response = array(
        'success' => $this->id,
    );
} else {
    $response = array(
        'error'   => true,
        'request' => $this->request,
    );
    $messages = array();
    $info     = $this->form->getMessages();
    if (isset($info['pasteform'])) {
        $info = $info['pasteform'];
    } elseif (isset($info['followupform'])) {
        $info = $info['followupform'];
    } else {
        throw new Exception('Invalid form data provided to view');
    }
    foreach ($info as $name => $errors) {
        if (!isset($this->form->{$name})) {
            throw new Exception('Invalid element: ' . $name);
        }
        $label = $this->form->$name->getLabel();
        $messages[] = array(
            'label'    => $label,
            'messages' => array_values($errors),
        );
    }
    $response['messages'] = $messages;
}
echo $this->json($response);
