<? 
$dijitParams = array(
    'title'         => 'Active Pastes',
    'class'         => 'tab',
    'href'          => $this->baseUrl() . '/api/spindle/paste/content/active-grid.html',
    'parseOnLoad'   => true,
);
$content = '';
if ('active' == $this->current) {
    unset($dijitParams['href']);
    $dijitParams['selected'] = true;
    if (!$content = $this->cache()->load('active-grid.html')) {
        $content = $this->render('paste/content/active-grid.phtml');
        $this->cache()->save('active-grid.html', $content);
    }
}

echo $this->contentPane('active', $content, $dijitParams);
