<?  
$this->dojo()->enable();
$this->current = 'display';
$this->tabContainer()->captureStart('pastebin', array('class' => 'paste-tab')) ?>
<?= $this->render('paste/_about.phtml') ?>
<?= $this->render('paste/_new-paste.phtml') ?>
<?= $this->render('paste/_active.phtml') ?>
<?= $this->render('paste/_display.phtml') ?>
<?= $this->render('paste/_followup.phtml') ?>
<?= $this->tabContainer()->captureEnd('pastebin') ?>
