<?
if (Zend_Controller_Front::getInstance()->getRequest()->getParam('nojs', false)) {
    $this->dojo()->disable();
    $content = preg_replace('#href="([^"]*)"#s', 'href="$1?nojs=true"', $content);
}
?>
<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?= $this->headTitle() ?> 
    <?= $this->headMeta() ?> 
    <?= $this->headLink() ?> 
    <?= $this->headStyle() ?> 
    <?= $this->dojo() ?> 
    <?= $this->headScript() ?> 
</head>
<body class="tundra">
    <?  $this->borderContainer()->captureStart('layout', array('design' => 'headline')) ?>
    <?= $this->render('_headline.phtml') ?>
    <?= $this->render('_mainPane.phtml') ?>
    <?= $this->render('_navPane.phtml') ?>
    <?= $this->render('_footer.phtml') ?>
    <?= $this->borderContainer()->captureEnd('layout') ?></body>
</html>
