<?
$content = $this->render('_layout.phtml');
if (Zend_Controller_Front::getInstance()->getRequest()->getParam('nojs', false)) {
    $this->dojo()->disable();
    $content = preg_replace('#href="([^"]*)"#s', 'href="$1?nojs=true"', $content);
}
?>
<html>
<head>
    <?= $this->headTitle() ?> 
    <?= $this->headMeta() ?> 
    <?= $this->headLink() ?> 
    <?= $this->headStyle() ?> 
    <?= $this->dojo() ?> 
    <?= $this->headScript() ?> 
</head>
<body class="tundra">
    <?= $content ?> 
</body>
</html>
